name: Build-LLVM-Dependence-msvc

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  CC: cl
  CXX: cl

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project

      - name: Install dependencies
        run: |
          echo Install dependencies...
          choco install winflexbison pkgconfiglite
          pip install meson mako

      - name: Configure
        run: |
          mkdir build
          cd build
          "C:\Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && cmake -G Ninja -DCMAKE_INSTALL_PREFIX=D:/a/mesa/mesa/build/install -DLLVM_ENABLE_PROJECTS="clang;libclc" -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT ../llvm
        shell: cmd

      - name: Build
        run: |
          cd build
          "C:\Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && ninja
        shell: cmd

      - name: Install
        run: |
          cd build
          ninja install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: builds
          path: build/install
