name: Build-LLVM-Dependence

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project

      - name: Install dependencies
        run: |
          echo Install dependencies...
          sudo apt-get update
          sudo apt-get install mingw-w64 wine64 wine binutils-mingw-w64-x86-64 ninja-build -y

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/home/runner/work/mesa/llvm-project/install -DLLVM_ENABLE_PROJECTS=all -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT ../llvm

      - name: Build
        run: |
          cd build
          ninja

      - name: Install
        run: |
          cd build
          ninja install
          ls -l

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: builds
          path: build/install
