# Build for Windows

name: Windows-LLVMpipe-MinGW

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CC: x86_64-w64-mingw32-gcc-posix
  CXX: x86_64-w64-mingw32-g++-posix
  WINDRES: x86_64-w64-mingw32-windres
  DESTDIR: /home/runner/work/mesa/mesa/build/install

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#       - name: Add deb repository
#         # You may pin to the exact commit or the version.
#         # uses: myci-actions/add-deb-repo@5275891305537d029f5f3fa7ed48d367ec0caf27
#         uses: myci-actions/add-deb-repo@10
#         with:
#           # repository line as it appears in the sources.list
#           repo: deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
#           # name of the repository, the name will be used for a new file in the /etc/apt/sources.list.d directory, the .list suffix will be added to the name
#           repo-name: ubuntu-deb-src-repo

      - name: Install dependencies
        #sudo add-apt-repository "deb-src http://archive.ubuntu.com/ubuntu jammy universe multiverse"
        run: |
          echo Install dependencies...
          sudo apt-get update
          sudo apt-get install wine64 wine binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64-posix g++-mingw-w64-x86-64-posix mingw-w64 ninja-build -y
          sudo apt-get build-dep mesa
          sudo apt-get remove gcc-mingw-w64-x86-64-win32 g++-mingw-w64-x86-64-win32
          sudo pip install meson mako
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all
      - name: Configure
        run: |
          echo Configure...
          echo $PATH
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
          LIBRARY_PATH=$LIBRARY_PATH:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
          pwd
          mkdir -p build/install
          meson --cross-file x86_64-w64-mingw32-cross-llvm.txt -D c_std=c17 -D cpp_std=c++17 -D gallium-drivers=swrast --buildtype=release build
      - name: Compile
        run: |
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
          LIBRARY_PATH=$LIBRARY_PATH:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
          ninja -C build/

      - name: Install
        run: ninja -C build/ install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: builds
          path: build/install
