# Build for Windows

name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo Install dependencies...
          choco install winflexbison pkgconfiglite
          pip install meson mako

      - name: Configure
        run: |
          echo Configure...
          mkdir build
          cd > tmp
          set /p pwd=<tmp
          meson --prefix="%pwd%/build/install" -D gallium-drivers=swrast --buildtype=release build

      - name: Compile
        run: ninja -C build/

      - name: Install
        run: ninja -C build/ install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: builds
          path: build/install
